import path from 'path';
import { fileURLToPath } from 'url';
import express from 'express';
import dotenv from 'dotenv';
dotenv.config();

// Create Express app
const app = express();

// Get directory name
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Serve static files generated by Vite
app.use(express.static(path.resolve(__dirname, './dist')));

// Define route for all other routes to serve the index.html
app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, './dist/index.html'));
});

// Start the Express server
const PORT =  process.env.PORT ||3000;
console.log(PORT);
app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server is running on port ${PORT}`);
});
